### ISSUE TITLE
Spec & Code Distinctions

### ISSUE THREAD

**Issue by Psirex** [lidofinance/dual-governance#30]
The list of differences between the spec/mechanism docs and the current codebase:

**Mechanism doc**

- [x] Usage of terms "Withdrawal NFT"/"wNFT"—The withdrawal NFT is used across the docs and spec, but the "wNFT" term is not. For Withdrawal NFT, the valid symbol is "unstETH." The "unstETH" is also used in the codebase. (fixed in #54)
  - Solution: use "unstETH" instead of wNFT in the docs (??)
- [x] _veto signalling escrow_ - in the DualGovernance & DualGovernanceState contracts methods to return escrow are called just `signallingEscrow()` (fixed in #34)
  - Solution: `signallingEscrow()` -> `vetoSignallingEscrow()`
- [x] `SignallingEscrowMinLockTime` in the code titled `ESCROW_ASSETS_UNLOCK_DELAY` (fixed in #34)
  - Solution: `ESCROW_ASSETS_UNLOCK_DELAY` -> `SIGNALLING_ESCROW_MIN_LOCK_TIME`
- [x] _An address having stETH or wstETH locked in the signalling escrow can trigger an immediate withdrawal of the locked tokens to ETH while keeping the resulting withdrawal NFT locked in the signalling escrow._ - not implemented at this moment (fixed in #34)
  - Solution: add to the current `Escrow` version
- [x] `ProposalExecutionMinTimelock` - titled `AFTER_SUBMIT_DELAY`
  - Solution: The `AFTER_SUBMIT_DELAY` is more consistent with the current `EmergencyProtectedTimelock` semantic. But in the specification may be additional mention that in the code, this parameter is set using the `AFTER_SUBMIT_DELAY` variable.
- [x] `FirstSealRageQuitSupport` - titled `FIRST_SEAL_THRESHOLD` (fixed in #34)
  - Solution: `FIRST_SEAL_THRESHOLD` -> `FIRST_SEAL_RAGE_QUIT_SUPPORT`
- [x] `SecondSealRageQuitSupport` - titled `SECOND_SEAL_THRESHOLD` (fixed in #34)
  - Solution: `SECOND_SEAL_THRESHOLD` -> `SECOND_SEAL_RAGE_QUIT_SUPPORT`
- [x] `DynamicTimelockMinDuration ` - titled `SIGNALLING_MIN_DURATION` (fixed in #34)
  - Solution: `SIGNALLING_MIN_DURATION` -> `DYNAMIC_TIMELOCK_MIN_DURATION`
- [x] `DynamicTimelockMaxDuration ` - titled `SIGNALLING_MAX_DURATION` (fixed in #34)
  - Solution: `SIGNALLING_MAX_DURATION` -> `DYNAMIC_TIMELOCK_MAX_DURATION`
- [x] `VetoSignallingDeactivationMaxDuration` - titled `SIGNALLING_DEACTIVATION_DURATION` (fixed in #34)
  - Solution: `SIGNALLING_DEACTIVATION_DURATION()` -> `VETO_SIGNALLING_DEACTIVATION_MAX_DURATION()`
- [x] 1. _All stETH and wstETH held by the rage quit escrow are sent for withdrawal via the regular Lido Withdrawal Queue mechanism, generating a set of batch withdrawal NFTs held by the rage quit escrow._ - Not transferred actually, only initiates this process, but it must be done in a standalone transactions (fixed in #54)
  - Solution: The description in the document was changed slightly 
- [x] The duration of the ETH claim timelock is a linear function in the code now (fixed in #34)
  - Solution: Make the function quadratic to match the doc
- [x] `TiebreakerExecutionTimelock` - this functionality is not implemented
  - Solution: The timelock was added in #21
 
**Specification doc**

- [x] `Executor.sol` - in the code, it is titled `OwnableExecutor` (fixed in #34)
  - Solution: `OwnableExecutor` -> `Executor`
- [x] wNFTs - see the first item in the mechanism doc differences (fixed in #54)
  - Solution: see the first item in the mechanism doc differences  
- [x] `cancelAllPendingProposals()` - titled `cancellAll()` (fixed in #34)
  - Solution: `cancellAll()` -> `cancelAllPendingProposals()`
- [x] ~~_the emergency protection delay is set to zero_ - doesn't tested such configuration~~
  - Solution: Such a scenario test was added into the test plan and will be implemented
- [x] **emergency protection timelock** - titled `AFTER_SCHEDULE_DELAY` (fixed in #54)
  - Solution: Add note in the specification, that this property is titled `AFTER_SUBMIT_DELAY` in the config.
- [x]  _i.e. disconnect executor contracts from the DG contracts and reconnect them to the Lido DAO Voting/Agent contract_ - currently, the whole timelock contract is reconnected to the DAO Voting. (fixed in #54)
  - Solution: Fix the spec description  
- [x] `VetoSignallingDeactivation` → `RageQuit` - transition also possible (fixed in #34)
  - Solution: Implement transition in the code
- [x] `DualGovernance.setTiebreakerCommittee()` - titled `DualGovernance.setTiebreakerProtection()` (fixed in #34)
  - Solution: `setTiebreakerProtection()` -> `setTiebreakerCommittee()` 
- [x] `DualGovernance.tiebreakerApproveProposal` - no such method because there is no additional timelock on such decisions
  - Solution: Implement timelock for tiebreaker decisions (was added in the #21)
- [x] `DualGovernance.tiebreakerScheduleProposal()` - titled `tiebreakerSchedule()` (fixed in #34)
  - Solution: `tiebreakerSchedule()` -> `tiebreakerScheduleProposal()`
- [x] `DualGovernance.submitProposal()` - titled `DualGovernance.submit()` (fixed in #34)
  - Solution: `submit()` -> `submitProposal()` 
- [x] `DualGovernance.scheduleProposal()` - in the code `DualGovernance.schedule()` (fixed in #34)
  - Solution: `schedule()` -> `scheduleProposal()` 
- [x] tiebreakerSchedule - doesn't call `activateNextState()` (fixed in #34)
  - Solution: Call `activateNextState` as the first step of the method
- [x] `Config.sol` - `Configuration.sol`
  - Solution: Update the name in the spec
- [x] ~~_Reverts if the call was unsuccessful._ - maybe not revert, but return bool + result and revert from the timelock. Maybe it will be helpful in the future to support possible failable calls~~ (?)
  - Solution: Decided to skip this feature for now
- [x] `SignallingEscrowMinLockTime` - titled `ESCROW_ASSETS_UNLOCK_DELAY` (fixed in #34)
  - Solution: 
- [x] `DualGovernance.signallingEscrow()` - shall we use the prefix get for views or not (?)
  - Solution: Update the getters across the contracts to start from the `get`, `is`, or `can` prefix. Exceptions are the immutable variables and constants.
- [x] `RageQuitEthClaimTimelock` - titled `rageQuitWithdrawalsTimelock` (fixed in #54)
  - Solution: Use the `RageQuitWithdrawals*` naming for the actions associated with the ETH withdrawals from the `Escrow`
- [x] `Escrow` - check the code snippets in the doc to satisfy the struct names in the code (fixed in #54)
  - Solution: The spec snippets were updated
- [x] withdrawal NFT / Withdrawal NFT - check the capitalization consistency in the docs
  - Solution: uncapitalized version is used in the spec (fixed in #54)
- [x] ~~`Escrow.lockUnstETH()` - also stores the references of the NFTs and owners. Maybe worth mentioning in the docs.~~
  - Solution: It doesn't affect the logic and is mostly required for the UI, so it's not so important from the specification perspective.
- [x] ~~`Escrow.markUnstETHFinalized()` - shall it also update finalized shares for each vetoer?~~ (?)
  - Solution: No need to finalize for particular user, so let's skip for gas efficiency
- [x] `Escrow.requestNextWithdrawalsBatch()` - titled `Escrow.requestWithdrawalsBatch()` (fixed in #34)
  - Solution: `Escrow.requestWithdrawalsBatch()` -> `Escrow.requestNextWithdrawalsBatch()`
- [x] _the function updates the count of withdrawal requests generated by all invocations_ - stores not only the count but also the IDs of the batches (fixed in #54)
  - Solution: update docs description 
- [x] `claimNextWithdrawalsBatch()` - signature of the method differs (fixed in #54)
  - Solution: update docs description 
- [x] `claimUnstETH()` - `claimWithdrawalRequests()` in the code (fixed in #34)
  - Solution: `claimWithdrawalRequests()` -> `claimUnstETH()` 
- [x] `withdrawWstEthAsEth()` - in the code `withdrawWstEth()` (fixed in #34)
  - Solution: `withdrawWstEth()` -> `withdrawWstEthAsEth()`
- [x] `EmergencyProtectedTimelock.cancelAllNonExecutedProposals()` - `cancelAll()` in the code (fixed in #34).
  - Solution: `cancelAll()` -> `cancelAllNonExecutedProposals()` (?)
- [x] `EmergencyProtectedTimelock.activateEmergencyMode()` - titled `emergencyActivate()` (fixed in #34)
  - Solution: `emergencyActivate()` -> `activateEmergencyMode()` 
- [x] `EmergencyProtectedTimelock.deactivateEmergencyMode()` - titled `emergencyDeactivate()` (fixed in #34)
  - Solution: `emergencyDeactivate()` -> `deactivateEmergencyMode()` 
- [x] ~~splitting `IConfiguration` into `IAdminExecutorConfiguration`, `ITimelockConfiguration`, and `IDualGovernanceConfiguration` may be excessive~~
  - Solution: Stay as is for now. It may be updated in the future with the interfaces refactoring.
